name: Update Data every week

# This section specifies the schedule (cron) to run the script

on:
    schedule:
       
        # Run every day at 8:00 AM Swedish time (CET/CEST)
        - cron: '0 6 * * *'
    workflow_dispatch: # Allows manual triggering of the action

jobs:
    update-data:
        runs-on: ubuntu-latest # Use the latest version of Ubuntu

        steps:
            #Step 1: Check out the code from the repo
            - name: Checkout repo
              uses: actions/checkout@v2

              # List files for debugging
            - name: List files
              run: ls -R

            # Step 2: Set up Python 3.x
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.x'

            # Step 3: Install dependencies
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r FPL_draft_project/requirements.txt

            # Step 4: Run the script
            - name: Run the script
              run: python FPL_draft_project/draft_scrape.py

            # Step 5: Commit and push the changes (.nojekyll included to force a redeployment)
            - name: Commit and push changes
              run: |
                git config --global user.name "GitHub Action"
                git config --global user.email "action@github.com"
                touch .nojekyll
                git add .nojekyll FPL_draft_project/draft_data.json FPL_draft_project/draft_data.log 
                git commit -m "Auto-update draft data" || echo "No changes to commit"
                git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/gorrast/gorrast.github.io.git
